"""testing

Revision ID: 299aea29cdd1
Revises: 5df168f5a4e2
Create Date: 2021-03-24 14:07:53.525628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299aea29cdd1'
down_revision = '5df168f5a4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=220), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
