"""Added new speed model

Revision ID: 2f42ccebe48a
Revises: 88dfa540b39a
Create Date: 2020-12-20 16:18:50.717865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f42ccebe48a'
down_revision = '88dfa540b39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('speed_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['speed_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speed')
    # ### end Alembic commands ###
