"""test

Revision ID: 5df168f5a4e2
Revises: 86d4148ae71d
Create Date: 2021-03-24 14:06:37.991024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df168f5a4e2'
down_revision = '86d4148ae71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=220), nullable=True))

    # ### end Alembic commands ###
