"""empty message

Revision ID: 647ded20ddce
Revises: 40b884bf933d
Create Date: 2021-03-14 12:58:18.836057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647ded20ddce'
down_revision = '40b884bf933d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('timestamp_start', sa.DateTime(), nullable=True),
    sa.Column('timestamp_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_timestamp_end'), ['timestamp_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_timestamp_start'), ['timestamp_start'], unique=False)

    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signups_timestamp'), ['timestamp'], unique=False)

    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('form_question', sa.String(length=140), nullable=True),
    sa.Column('form_options', sa.String(), nullable=True),
    sa.Column('form_course_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_timestamp'), ['timestamp'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('form_prompt_id', sa.Integer(), nullable=True),
    sa.Column('form_responses', sa.Integer(), nullable=True),
    sa.Column('form_course_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['form_prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=220), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_courses_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['teacher_id'], ['id'])
        batch_op.drop_column('teacher')

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reactions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reactions_course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'courses', ['reactions_course_id'], ['id'])
        batch_op.create_foreign_key(None, 'session', ['session_id'], ['id'])
        batch_op.drop_column('speed')
        batch_op.drop_column('emotions')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reactions_timestamp'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('session_id')
        batch_op.drop_column('reactions_course_id')
        batch_op.drop_column('reactions')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_courses_timestamp'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('status')
        batch_op.drop_column('icon')
        batch_op.drop_column('color')

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_timestamp'))

    op.drop_table('responses')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_timestamp'))

    op.drop_table('prompts')
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signups_timestamp'))

    op.drop_table('signups')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_timestamp_start'))
        batch_op.drop_index(batch_op.f('ix_session_timestamp_end'))

    op.drop_table('session')
    # ### end Alembic commands ###
