"""uh oh

Revision ID: 84265ca835bc
Revises: 04c84448efd6
Create Date: 2020-12-19 15:35:58.313725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84265ca835bc'
down_revision = '04c84448efd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'courses', 'user', ['teacher_id'], ['id'])
    op.drop_column('courses', 'teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    # ### end Alembic commands ###
