"""empty message

Revision ID: 90a48257c474
Revises: 84265ca835bc
Create Date: 2020-12-19 15:58:03.777404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a48257c474'
down_revision = '84265ca835bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('ix_courses_code')
        batch_op.create_foreign_key(None, 'user', ['teacher_id'], ['id'])
        batch_op.drop_column('code')
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('code', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("user_id", type_='foreignkey')
        batch_op.create_index('ix_courses_code', ['code'], unique=1)

    # ### end Alembic commands ###
