"""Creating live forms tables x4

Revision ID: 910c24df465b
Revises: 2a872675d9e5
Create Date: 2021-02-07 16:03:43.363380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910c24df465b'
down_revision = '2a872675d9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('form_question', sa.String(length=140), nullable=True),
    sa.Column('form_course_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_timestamp'), ['timestamp'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('form_prompt_id', sa.Integer(), nullable=True),
    sa.Column('form_responses', sa.Integer(), nullable=True),
    sa.Column('form_course_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['form_prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('live_forms_prompts', schema=None) as batch_op:
        batch_op.drop_index('ix_live_forms_prompts_timestamp')

    op.drop_table('live_forms_prompts')
    with op.batch_alter_table('live_forms_responses', schema=None) as batch_op:
        batch_op.drop_index('ix_live_forms_responses_timestamp')

    op.drop_table('live_forms_responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_forms_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('form_prompt_id', sa.INTEGER(), nullable=True),
    sa.Column('form_responses', sa.INTEGER(), nullable=True),
    sa.Column('form_course_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['form_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['form_prompt_id'], ['live_forms_responses.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_forms_responses', schema=None) as batch_op:
        batch_op.create_index('ix_live_forms_responses_timestamp', ['timestamp'], unique=False)

    op.create_table('live_forms_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('form_question', sa.VARCHAR(length=140), nullable=True),
    sa.Column('form_course_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['form_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_forms_prompts', schema=None) as batch_op:
        batch_op.create_index('ix_live_forms_prompts_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_timestamp'))

    op.drop_table('responses')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_timestamp'))

    op.drop_table('prompts')
    # ### end Alembic commands ###
