"""Signups table

Revision ID: 981e83383fe9
Revises: 16ccc6bcc907
Create Date: 2020-12-19 23:12:04.190314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981e83383fe9'
down_revision = '16ccc6bcc907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signups')
    # ### end Alembic commands ###
