"""Updated models

Revision ID: 99d471b46990
Revises: b9af9dd9c27d
Create Date: 2020-12-24 14:00:05.294325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d471b46990'
down_revision = 'b9af9dd9c27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('speed', sa.INTEGER(), nullable=True),
    sa.Column('speed_course_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['speed_course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
