"""upgrade

Revision ID: 9bd11faabcc2
Revises: 99d471b46990
Create Date: 2020-12-24 14:33:47.815591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd11faabcc2'
down_revision = '99d471b46990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index('ix_status_timestamp')

    op.drop_table('status')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status_course_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['status_course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.create_index('ix_status_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
