"""Update name

Revision ID: c90aabd7554b
Revises: 9bd11faabcc2
Create Date: 2020-12-24 15:16:09.119912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90aabd7554b'
down_revision = '9bd11faabcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reactions', sa.Integer(), nullable=True))
        batch_op.drop_column('emotions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotions', sa.INTEGER(), nullable=True))
        batch_op.drop_column('reactions')

    # ### end Alembic commands ###
