"""Probably gonna fail

Revision ID: ca475ba36048
Revises: ac4885c57753
Create Date: 2020-12-19 15:15:12.456844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca475ba36048'
down_revision = 'ac4885c57753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.drop_index('ix_courses_teacher', table_name='courses')
    op.create_foreign_key(None, 'courses', 'user', ['teacher_id'], ['id'])
    op.drop_column('courses', 'teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_index('ix_courses_teacher', 'courses', ['teacher'], unique=1)
    op.drop_column('courses', 'teacher_id')

    # ### end Alembic commands ###
