"""New timestamp column

Revision ID: d759151613ab
Revises: 0ab9fee1ba11
Create Date: 2020-12-24 13:26:27.899242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd759151613ab'
down_revision = '0ab9fee1ba11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_courses_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reactions_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_signups_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_status_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_timestamp'))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signups_timestamp'))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reactions_timestamp'))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
