"""add icon column

Revision ID: dab67a8b5aa6
Revises: 910c24df465b
Create Date: 2021-02-11 16:31:29.470395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab67a8b5aa6'
down_revision = '910c24df465b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=220), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
