"""Delete speed column in reactions

Revision ID: dbfd2a90f679
Revises: 981e83383fe9
Create Date: 2020-12-20 14:50:56.579073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfd2a90f679'
down_revision = '981e83383fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.drop_column('speed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speed', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
