"""Updated reactions table

Revision ID: e90d30611dcf
Revises: 099d3f6a9697
Create Date: 2020-12-19 11:32:59.827437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90d30611dcf'
down_revision = '099d3f6a9697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('emotions', sa.Integer(), nullable=True))
    op.add_column('reactions', sa.Column('speed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactions', 'speed')
    op.drop_column('reactions', 'emotions')
    # ### end Alembic commands ###
